### PR TITLE
Create hero atom

### PR DESCRIPTION
**Pull request by RDO34**
<div align="center"></div>

### CODE REVIEW

**Review by spn1 — COMMENTED** [review]
🌮

**Review by spn1 — APPROVED** [review]
🌮

**Review by spn1 — APPROVED** [review]

**Comment by spn1** [comment]
cant review :c

**Review by SteWearing — COMMENTED** [review]
Screen Shot 2019-05-12 at 16 08 03

👎 data-testid 👎                 🌮 data-test-id 🌮

**Pull request merged**
